export const TransationHistory = ({
  one,
  two,
  three,
  four,
  five,
  six,
  seven,
  eight,
  nine,
  ten,
  eleven,
  twelve,
  thirteen,
  fourteen,
  fifteen,
  sixteen,
  seventeen,
  eighteen,
  nineteen,
  twenty,
}) => {
  return (
    <table>
      <thead>
        <tr>
          <th>Type</th>
          <th>Amount</th>
          <th>Currency</th>
        </tr>
      </thead>

      <tbody>
        <tr>
          <td>{one.type}</td>
          <td>{one.amount}</td>
          <td>{one.currency}</td>
        </tr>
        <tr>
          <td>{two.type}</td>
          <td>{two.amount}</td>
          <td>{two.currency}</td>
        </tr>
        <tr>
          <td>{three.type}</td>
          <td>{three.amount}</td>
          <td>{three.currency}</td>
        </tr>
        <tr>
          <td>{four.type}</td>
          <td>{four.amount}</td>
          <td>{four.currency}</td>
        </tr>
        <tr>
          <td>{five.type}</td>
          <td>{five.amount}</td>
          <td>{five.currency}</td>
        </tr>
        <tr>
          <td>{six.type}</td>
          <td>{six.amount}</td>
          <td>{six.currency}</td>
        </tr>
        <tr>
          <td>{seven.type}</td>
          <td>{seven.amount}</td>
          <td>{seven.currency}</td>
        </tr>
        <tr>
          <td>{eight.type}</td>
          <td>{eight.amount}</td>
          <td>{eight.currency}</td>
        </tr>
        <tr>
          <td>{nine.type}</td>
          <td>{nine.amount}</td>
          <td>{nine.currency}</td>
        </tr>
        <tr>
          <td>{ten.type}</td>
          <td>{ten.amount}</td>
          <td>{ten.currency}</td>
        </tr>
        <tr>
          <td>{eleven.type}</td>
          <td>{eleven.amount}</td>
          <td>{eleven.currency}</td>
        </tr>
        <tr>
          <td>{twelve.type}</td>
          <td>{twelve.amount}</td>
          <td>{twelve.currency}</td>
        </tr>
        <tr>
          <td>{thirteen.type}</td>
          <td>{thirteen.amount}</td>
          <td>{thirteen.currency}</td>
        </tr>
        <tr>
          <td>{fourteen.type}</td>
          <td>{fourteen.amount}</td>
          <td>{fourteen.currency}</td>
        </tr>
        <tr>
          <td>{fifteen.type}</td>
          <td>{fifteen.amount}</td>
          <td>{fifteen.currency}</td>
        </tr>
        <tr>
          <td>{sixteen.type}</td>
          <td>{sixteen.amount}</td>
          <td>{sixteen.currency}</td>
        </tr>
        <tr>
          <td>{seventeen.type}</td>
          <td>{seventeen.amount}</td>
          <td>{seventeen.currency}</td>
        </tr>
        <tr>
          <td>{eighteen.type}</td>
          <td>{eighteen.amount}</td>
          <td>{eighteen.currency}</td>
        </tr>
        <tr>
          <td>{nineteen.type}</td>
          <td>{nineteen.amount}</td>
          <td>{nineteen.currency}</td>
        </tr>
        <tr>
          <td>{twenty.type}</td>
          <td>{twenty.amount}</td>
          <td>{twenty.currency}</td>
        </tr>
      </tbody>
    </table>
  );
};
